version: "2.0"
type: node-port
services:
  vm:
    image: filswan/ubuntu-ssh:22.04
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyz8A/a8EPUCuGoV8qqSbhCYUfMDgYHUF4cGQHVlOCcUoV6dLKyCjivyF2R5r4313lCgYFvQBDfNOkOR9EcvhF/hyPJOLY5MD1lCO+8emeXvnZGItJGlEh11QfySbrzoqx3pL78v17n0g7ZbX57hctM066KOYB7oW0vr+sIAQrbOaZK1dsTWMXaZ0FkS4OvBNnQEj7nMPXsFeZq5uF7uoNOs1XjxTYTc+ajTSq+A1hzRLjoWupKY1znmit9Z1P+M/wsoPikKBzT/WHDjEhMHovzicOAnqb0Qik7+oSXNSUPGpbXht0ZueIyv1kdi6/YEBee+oTyCjDiMGKkee4g+4tTwZH2ulJdO1uQEJX4DodSciVzMHBGgmpatNpDDWno4svxCVRbZBA5673PIRv6+zm3m/Xemoq7Cm0cPb/A2w2QtltejKJXqJJvTI+J7JHy9rWbseRsGSJVkHHMBLP8+9mo4+krqFshQASQIKHriY4geRBtZ6hpQLx4Uz+BOrtmFk=
    expose:
        - port: 22
        - port: 8080
deployment:
  vm:
    lagrange:
      count: 1
